export default function(){
    return(
        <nav>
            <ul>
                <li>Home</li>
                <li>Products
                    <ul>
                        <li>Dashboard</li>
                        <li>Drafts</li>
                        <li>Released</li>
                        <li>Scheduled</li>
                    </ul>
                </li>
                <li>Costumers</li>
                <li>Shop</li>
                <li>Income</li>
                <li>Promote</li>
            </ul>
        </nav>
    )
}